limit_req_zone $binary_remote_addr zone=mylimit:10m rate=100r/s;

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        limit_req zone=mylimit burst=200 nodelay;
        try_files $uri $uri/ /index.html;
    }
}
