export const LOGIN = {
  BRAND: "webHyre.ai",
  SUBTITLE: "AI Hiring Platform",
  SIGN_IN_LABEL: "Sign in with your work account",
  SIGNING_IN_LABEL: "Signing you in\u2026",
  EMAIL_LABEL: "Email",
  PASSWORD_LABEL: "Password",
  FULL_NAME_LABEL: "Full Name",
  ORG_NAME_LABEL: "Organization Name",
  SIGN_IN_BTN: "Sign In",
  SIGN_UP_BTN: "Create Account",
  GOOGLE_LABEL: "Continue with Google",
  NO_ACCOUNT: "Don\u2019t have an account?",
  HAS_ACCOUNT: "Already have an account?",
  SIGN_UP_LINK: "Sign up",
  SIGN_IN_LINK: "Sign in",
  FOOTER: "Only authorized personnel can access this platform.",
  PASSWORD_MIN_LENGTH: "Password must be at least 8 characters",
  INVALID_EMAIL: "Please enter a valid email address",
} as const;
