export const API_ENDPOINTS = {
  AUTH_ME: "/auth/me",
  AUTH_REFRESH: "/auth/refresh",
  AUTH_GOOGLE: "/auth/google",
  AUTH_LOGOUT: "/auth/logout",
  CHAT_CHATS: "/chat/chats",
  CHAT_MESSAGES: "/chat/messages",
  CHAT_CHAT_DELETE: "/chat/chats",
  APPLICATIONS: "/applications/",
  APPLICATIONS_BY_ID: "/applications/",
  HIRING_REQUESTS: "/hiring-requests/",
  HIRING_REQUESTS_DEPARTMENTS: "/hiring-requests/departments",
  HIRING_REQUESTS_LOCATIONS: "/hiring-requests/locations",
  HIRING_REQUESTS_TYPES: "/hiring-requests/types",
  HIRING_REQUESTS_STATUS: "/hiring-requests/:id/status",
  ROUNDS: "/rounds/",
  USERS: "/users/",
  SLOTS: "/slots/",
  SLOTS_CREATE: "/slots/",
  SLOTS_EMPLOYEE: "/slots/by-employee",
  FORMS_VALIDATE: "/forms/validate/",
  FORMS_SUBMIT: "/forms/",
  ASK_FORM: "/ask-form",
  REVIEWS_ROUND: "/reviews/round",
  FINAL_VERDICT: "/applications/{candidate_id}/final-verdict",
  FINAL_VERDICTS: "/applications/final-verdicts",
  INTERVIEWS: "/interviews",
  INTERVIEWS_BOOKING: "/interviews/booking",
  INTERVIEWS_SCHEDULING: "/interviews/scheduling",
  ALERTS: "/alerts",
  FORMS_NOTIFY: "/forms/notify",
  EVENTS_BY_CANDIDATE: "/events/by-candidate/",
  AUTH_LOGIN: "/auth/login",
  AUTH_SIGNUP: "/auth/signup",
  AUTH_CHANGE_PASSWORD: "/auth/change-password",
  AUTH_INVITES: "/auth/invites",
  AUTH_ACCEPT_INVITE: "/auth/accept-invite",
  ADMIN_USERS: "/admin/users",
  ADMIN_USERS_INVITES: "/admin/users/invites",
  SETTINGS: "/settings",
  SUPERADMIN_APPS: "/superadmin/apps",
  ADMIN_APPS: "/admin/apps",
  SUPERADMIN_TENANTS: "/superadmin/tenants",
  ADMIN_ORGANIZATION: "/admin/organization",
  AI_SCREENING: "/hiring-requests/{hiring_request_id}/ai/screening",
  AI_INTERVIEWS: "/hiring-requests/{hiring_request_id}/ai/candidates/{candidate_id}/interviews",
  AI_MOVE_TO_SCREENING: "/hiring-requests/{hiring_request_id}/ai/candidates/{candidate_id}/move-to-screening",
  AI_MOVE_TO_INTERVIEW: "/hiring-requests/{hiring_request_id}/ai/candidates/{candidate_id}/move-to-interview",
  AI_QUESTIONS: "/hiring-requests/{hiring_request_id}/ai/questions",
  APPLICATION_ROUND_STATUS: "/applications/{candidate_id}/round-status",
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PER_PAGE: 10,
  DEFAULT_CHATS_PAGE_SIZE: 20,
  DEFAULT_CHAT_MESSAGES_LIMIT: 20,
  DEFAULT_CMD_PALETTE_PAGE_SIZE: 5,
  APPLICATIONS_PER_PAGE: 15,
  APPLICATIONS_SEARCH_SIZE: 20,
  INTERVIEWS_PER_PAGE: 20,
} as const;

export const FILTER_DEFAULTS = {
  ALL: "all",
} as const;
