export const EDIT_EMPLOYEE_LABELS = {
  TITLE: "Edit Employee",
  SUBTITLE: (name: string) => `Update profile details for ${name}`,
  STAGES: {
    IDENTITY: "Identity",
    ROLE: "Role",
    EMPLOYMENT: "Employment",
  } as const,
  NAME: "Name",
  EMAIL: "Email",
  PERSONAL_EMAIL: "Personal Email",
  HRMS_ID: "HRMS ID",
  EMP_ID: "Employee ID",
  DESIGNATION: "Designation",
  DEPARTMENT: "Department",
  BAND: "Band",
  USER_TYPE: "User Type",
  STATUS: "Status",
  CONTACT: "Contact Number",
  WORK_MODE: "Work Mode",
  DELIVERY_STATUS: "Delivery Status",
  WORK_LOCATION: "Work Location Type",
  DOJ: "Date of Joining",
  DOE: "Date of Exit",
  DATE_OF_BIRTH: "Date of Birth",
  INTERNSHIP_DURATION: "Internship Duration (months)",
  SKILLS: "Skills",
  CANCEL: "Cancel",
  SAVE: "Save Changes",
  SAVING: "Saving...",
  ERROR_FALLBACK: "Failed to update employee",
} as const;

export const EDIT_EMPLOYEE_PLACEHOLDERS = {
  EMP_ID: "Employee ID",
  NAME: "e.g. Jane Doe",
  EMAIL: "e.g. jane.doe@company.com",
  PERSONAL_EMAIL: "e.g. jane@personal.com",
  HRMS_ID: "e.g. HRMS-12345",
  DESIGNATION: "e.g. Software Engineer",
  DEPARTMENT: "e.g. Engineering",
  BAND: "e.g. L3",
  USER_TYPE: "e.g. Full-time",
  STATUS: "e.g. Active",
  CONTACT: "e.g. +91 98765 43210",
  WORK_MODE: "e.g. Hybrid",
  DELIVERY_STATUS: "e.g. Billable",
  WORK_LOCATION: "e.g. Bangalore",
  DOJ: "Select date of joining",
  DOE: "Select date of exit",
  DATE_OF_BIRTH: "Select date of birth",
  INTERNSHIP_DURATION: "e.g. 6",
  SKILLS: "e.g. React, TypeScript, Node.js",
} as const;

export const EDIT_EMPLOYEE_STAGE_ORDER = [
  "identity",
  "role",
  "employment",
] as const;
