import type { TimelineStep } from "@/app/dashboard/hiring-requests-detail/components/timeline/timeline.types";

export const mockSteps: TimelineStep[] = [
  {
    id: "1",
    title: "Resume Uploaded",
    description: "Candidate uploaded resume",
    status: "success",
    date: "2026-06-01",
  },
  {
    id: "2",
    title: "Screening Started",
    description: "HR started screening",
    status: "success",
    date: "2026-06-01",
  },
  {
    id: "3",
    title: "Screening Result",
    description: "Candidate selected in screening round",
    status: "success",
    date: "2026-06-02",
  },
  {
    id: "4",
    title: "Queued for Interview Round 1",
    description: "Waiting for scheduling",
    status: "queued",
    date: "2026-06-02",
  },
  {
    id: "5",
    title: "Round 1 Scheduled",
    description: "Interview scheduled with Sandheep Kumar",
    status: "success",
    actor: "Sandheep Kumar",
    date: "2026-06-03",
  },
  {
    id: "6",
    title: "Round 1 Started",
    description: "Interview in progress",
    status: "success",
    actor: "Sandheep Kumar",
    date: "2026-06-03",
  },
  {
    id: "7",
    title: "Round 1 Ended",
    description: "Interview completed",
    status: "success",
    actor: "Sandheep Kumar",
    date: "2026-06-03",
  },
  {
    id: "8",
    title: "Waiting for Interview Feedback",
    description: "Interviewer submitting remarks",
    status: "waiting",
    date: "2026-06-03",
  },
  {
    id: "9",
    title: "Interview 1 Result",
    description: "AI Decision: Selected",
    status: "success",
    date: "2026-06-04",
  },
  {
    id: "10",
    title: "HR Decision Requested",
    description: "Request sent to HR",
    status: "success",
    date: "2026-06-04",
  },
  {
    id: "11",
    title: "Waiting HR Decision",
    description: "HR reviewing candidate",
    status: "waiting",
    date: "2026-06-05",
  },
  {
    id: "12",
    title: "HR Selected for Round 2",
    description: "Assigned to Pranav",
    status: "success",
    actor: "Pranav",
    date: "2026-06-05",
  },
  {
    id: "13",
    title: "Queued for Interview Round 2",
    description: "Waiting for scheduling",
    status: "queued",
    date: "2026-06-05",
  },
  {
    id: "14",
    title: "Round 2 Scheduled",
    description: "Interview scheduled with Pranav",
    status: "success",
    actor: "Pranav",
    date: "2026-06-06",
  },
  {
    id: "15",
    title: "Round 2 Started",
    description: "Interview in progress",
    status: "success",
    actor: "Pranav",
    date: "2026-06-06",
  },
  {
    id: "16",
    title: "Round 2 Ended",
    description: "Interview completed",
    status: "success",
    actor: "Pranav",
    date: "2026-06-06",
  },
  {
    id: "17",
    title: "Waiting for Final Feedback",
    description: "Interviewer submitting remarks",
    status: "waiting",
    date: "2026-06-06",
  },
  {
    id: "18",
    title: "Interview 2 Result",
    description: "AI Decision: Selected",
    status: "success",
    date: "2026-06-07",
  },
  {
    id: "19",
    title: "Final HR Decision Requested",
    description: "HR final approval requested",
    status: "success",
    date: "2026-06-07",
  },
  {
    id: "20",
    title: "Waiting Final HR Decision",
    description: "Final approval pending",
    status: "waiting",
    date: "2026-06-07",
  },
];