export const CREATE_EMPLOYEE_LABELS = {
  TITLE: "Add employee",
  ICON: "bx bx-user-plus",
  EMP_ID: "Employee ID",
  NAME: "Name",
  EMAIL: "Work email",
  DESIGNATION: "Designation",
  DEPARTMENT: "Department",
  OPTIONAL: "optional",
  EMP_ID_PLACEHOLDER: "e.g. EMP009",
  NAME_PLACEHOLDER: "Full name",
  EMAIL_PLACEHOLDER: "nina.v@example.com",
  DESIGNATION_PLACEHOLDER: "e.g. Software Engineer",
  DEPARTMENT_PLACEHOLDER: "e.g. Engineering",
  CANCEL: "Cancel",
  SUBMIT: "Add employee",
  SUBMITTING: "Adding...",
  ERR_EMP_ID: "Employee ID is required",
  ERR_NAME: "Name is required",
  ERR_EMAIL: "Work email is required",
  ERR_EMAIL_INVALID: "Enter a valid work email",
  ERR_GENERIC: "Failed to add employee",
  TOAST_SUCCESS: "Employee added",
} as const;
